<div class="clearfix">
	<form  class="form" method="POST">
		<input type="hidden" name="action" value="v_order">
		
	<p>
		<p>Status : <?=htmlentities($cart->getStatus())?></p>
		<p>Prix : <?=htmlentities($cart->getPrice())?></p>
		<p>Date : <?=htmlentities($cart->getDate())?></p>
	</p>
	<?php require('apps/cart_elem.php'); ?>
		<button type="submit" class="btn btn-default">Valider le panier</button>
	</form>
</div>		
	<!-- 	<input type="hidden" class="action" value="terminé"> -->