<div class="row">
	<div class="col-sm-2">
		<div class="thumbnail">
			<img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
		</div>
	</div>
	<div class="col-sm-10">
		<div class="panel panel-default">
			<div class="panel-heading">
				<strong>
					<?=htmlentities($comment->getAuthor()->getLogin())?>
					<?=htmlentities($comment->getProduct()->getLogin())?>
				</strong> 
				<span class="text-muted"><?=htmlentities($comment->getDate())?></span>
			</div>
			<div class="panel-body">
				<?=htmlentities($comment->getContent())?>
			</div>
		</div>
	</div>
</div>