<footer class="footer">
	<div class="containerFooter">
		<ul class="nav navbar-nav text-center">
			<li class="text-center"><a href="index.php?page=categories">Les catégories</a></li>
			<li class="text-center"><a href="index.php?page=create_category">Les produits</a></li>
			<li class="text-center"><a href="index.php?page=create_product">Nous contacter</a></li>
			<li class="text-center"><a href="index.php?page=user">Mon profil</a></li>
			<li class="text-center"></li>
		</ul>
		<div class="logo"><img src="http://www.3sfrance.com/public/img/big/LOGO-PAYPAL-MP-279x300.png" alt="logo Paypal"></div>
		<strong><p class="text-center">2017 - A N I M A N I A X - All Right Reserved &copy</p></strong>
	</div>
</footer>