<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.php">Animaniax</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="<?=$page_profile?>"><a href="index.php?page=user">Mon profil</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<li class="<?=$page_logout?>"><a href="index.php?page=logout">Se déconnecter</a></li>
					<input type="text" name="search" placeholder="Que recherchez-vous ?"/>
				</li>
				<li class="navbar-right"><a href="index.php?page=cart"><img style="width:100%;" src="public/images/cart.png"></a></li>
			</ul>
		</div>
		<p>Bonjour <strong><?=htmlentities($_SESSION['email'])?></strong>, vous êtes maintenant connecté(e)!</p>
	</div>
</nav>