<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="sr-only">Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.php">Animaniax</a>
		</div>
		<div class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li class="<?=$page_cat?>">
					<a href="index.php?page=categories">Les catégories</a>
				</li>
				<li class="<?=$page_nllecat?>">
					<a href="index.php?page=create_category">Nouvelle catégorie</a>
				</li>
				<li class="<?=$page_nvprod?>">
					<a href="index.php?page=create_product">Nouveau produit</a>
				</li>
				<li class="<?=$page_profile?> ">
					<a href="index.php?page=user">Mon profil</a>
				</li>
				<li class="<?=$page_logout?>"><a href="index.php?page=logout">Se déconnecter</a></li>
				<input type="text" name="search" placeholder="Que recherchez-vous ?"/>
				<li class="navbar-right">
					<a href="index.php?page=cart">
						<img style="width:15%;" src="public/images/cart.png">
					</a>
				</li>
			</ul>
		</div>
		<p>Bonjour <strong><?=htmlentities($_SESSION['email'])?></strong>, vous êtes maintenant connecté(e) en tant qu'<strong>admin</strong> !</p>
	</div>
</nav>