<div class="content">
	<a href="#">
		<h1>Chat siamois</h1>
		<img src="https://goo.gl/images/0v2cQV" alt="chat">
	</a>
	<h2>Description</h2>
	<p>Le Siamois est une race de chat originaire de Thaïlande, caractérisée par un physique de type oriental. Le Siamois est une race très populaire qui durant toute son histoire a connu bien des évolutions. L'origine de ce félin se perd dans la nuit profonde de l'Orient. C'est en 1884 que les premiers chats Siamois firent leur apparition en Angleterre.
	</p>

</div>
<?php
// require('apps/create_comment.php');
// require('apps/comments.php');