<div class="content">
	
		<h1><?=htmlentities($product->getName())?></h1>
		<img class=" pull-left" style="width:20%; padding-right:30px;" src="<?=htmlentities($product->getPicture())?>" alt="chat">
	
	<h2><?=htmlentities($product->getName())?></h2>
	<p><?=htmlentities($product->getDescription())?></p>
	<a class="button btn btn-info" href="">Rajouter au panier</a>
	<p><?=htmlentities($product->getPrice())?> euros</p>
	<p style="padding-top:20px;">Il est reste <?=htmlentities($product->getQuantity())?></p>


</div>
<div class="clearfix"></div>
<?php
require('apps/create_comment.php');
require('apps/comments.php'); 
?>