
<div class="content">
	
		<h1><?=htmlentities($product->getName())?></h1>
		<img class=" pull-left thumbnail" style="width:20%; margin-right:30px;" src="<?=htmlentities($product->getPicture())?>" alt="chat">
	
	<h2><?=htmlentities($product->getDescription())?></h2>
	<form class="form" method="POST">
		<input type="hidden" name="action" value="add">
		<input type="hidden" name="id_product" value="<?=htmlentities($product->getId())?>">
	
		<?php require('apps/cart_in.php'); ?>
	</form>

	<p><?=htmlentities($product->getPrice())?> euros</p>
	<p style="padding-top:20px;">Il en reste <?=htmlentities($product->getQuantity())?></p>



</div>
<div class="clearfix"></div>

<?php 
	require('apps/create_comment.php');
    require('apps/comments.php'); 
?>
