
<div class="col-md-4">
        <div class="product-item">
            <div class="pi-img-wrapper">
              <a href="index.php?page=product&id=<?=$product->getId()?>">
               <img style=width="300" height="200"src="<?=htmlentities($product->getPicture())?>" alt="picture animals" class="picture_animals">
              <p class= "products_name">Name <?=htmlentities($product->getName())?></p>
              <p class ="products_price"><?=htmlentities($product->getPrice())?></p>
            </div>
              <a href="javascript:;" class="btn add2cart">Add to cart</a>
        	<div class="sticker sticker-new"></div>
        </div>
</div>