<h1>Register</h1>
<form class="form" method="POST">
	<input type="hidden" name="action" value="register">
	<div class="form-group">
		<label for="email">Email</label>
		<input type="email" class="form-control" id="email" name="email" placeholder="Email">
	</div>
	<div class="form-group">
		<label for="password1">Password</label>
		<input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="password2">Retaper votre password</label>
		<input type="password" class="form-control" id="password2" name="password2" placeholder="Password">
	</div>
	<div class="form-group">
		<label for="name">Votre nom</label>
		<input type="text" class="form-control" id="name" name="name" placeholder="Name">
	</div>
	<div class="form-group">
		<label for="address">Votre adresse</label>
		<input type="text" class="form-control" id="address" name="address" placeholder="Adresse">
	</div>
	<div class="form-group">
		<label for="city">Votre ville</label>
		<input type="text" class="form-control" id="city" name="city" placeholder="City">
	</div>
	<div class="form-group">
		<label for="birthdate">Date de naissance</label>
		<input type="date" class="form-control" id="birthdate" name="birthdate">
	</div>
	<button type="submit" class="btn btn-default">Envoyer</button>
</form>