<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
		<link rel="stylesheet" type="text/css" href="public/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="public/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="public/style.css">
		<script type="text/javascript" src="public/script/script.js"></script>
		<title>Animaniax</title>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>

		<script src="../public/script/jquery-3.1.1.min.js"></script>
		<script src="../js/bootstrap.min.js"></script>
	</body>
</html>