<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="UTF-8">
		<link rel="stylesheet" type="text/css" href="styles/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="styles/bootstrap-theme.min.css">
		<link rel="stylesheet" type="text/css" href="styles/style.css">
		<title>Animaniax</title>
	</head>
	<body>
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
	</body>
</html>