<article class="bloc_profile clear_fix">
	<div class="content_profile">
		<h2>Modifier mon profil</h2>
		<p>Votre email : <?=htmlentities($user->getEmail())?></p>
		<p> Votre date de naissance : <?=htmlentities($user->getBirthdate())?> </p>
		<p> Votre adresse  : <?=htmlentities($user->getAddress())?></p>
		<p> Votre ville : <?=htmlentities($user->getCity())?></p>
		<a class="button btn btn-info" href="index.php?page=orders">Mes commandes</a>
	</div>
</article>